import React, { useEffect, useMemo, useRef, useState } from 'react'
import { Modal } from '@renderer/components/ui/Modal'
import { Button } from '@renderer/components/ui/Button'
import { useActiveProject } from '@renderer/contexts/ProjectContext'
import { useProjectsGroups } from '@renderer/contexts/ProjectsGroupsContext'

/**
 * NOTE:
 * Topic chats are now only GROUP_TOPIC and PROJECT_TOPIC.
 * Topic chat ids are generated by ChatsTools.createTopicChat (exposed via the app's chats layer).
 * This modal only collects a title and delegates creation to the backend.
 */

type Props = {
  isOpen: boolean
  onClose: () => void
  // Receives the created topic chat context (including generated id) so ChatView can navigate to it.
  onTopicCreated: (ctx: any) => void
}

export default function ChatTopicCreateModal({ isOpen, onClose, onTopicCreated }: Props) {
  const { projectId: activeProjectId } = useActiveProject()
  const { activeSelectionType, activeGroupId } = useProjectsGroups()

  const [title, setTitle] = useState('')
  const [isCreating, setIsCreating] = useState(false)
  const inputRef = useRef<HTMLInputElement | null>(null)

  useEffect(() => {
    if (!isOpen) return
    setTitle('')
    setIsCreating(false)
  }, [isOpen])

  const scopeLabel = useMemo(() => {
    if (activeSelectionType === 'group') return 'Group'
    return 'Project'
  }, [activeSelectionType])

  const canCreate = useMemo(() => {
    if (!title.trim()) return false
    if (activeSelectionType === 'group') return !!activeGroupId
    return !!activeProjectId
  }, [title, activeSelectionType, activeGroupId, activeProjectId])

  const handleCreate = async (e?: React.FormEvent) => {
    if (e) e.preventDefault()
    if (!canCreate) return

    setIsCreating(true)
    try {
      // We intentionally call into the chats layer which must wrap ChatsTools.createTopicChat.
      // The returned chat should include the generated topic chat id.
      const chat = await window.chatsService.createTopicChat(
        activeSelectionType === 'group' ? 'group' : 'project',
        activeSelectionType === 'group' ? activeGroupId! : activeProjectId!,
        title.trim()
      )

      if (!chat) throw new Error('Failed to create topic chat')

      onTopicCreated(chat.context)
      onClose()
    } catch (err) {
      console.error('Failed to create topic chat', err)
      // Keep modal open so user can retry
      setIsCreating(false)
      inputRef.current?.focus()
    }
  }

  return (
    <Modal
      isOpen={isOpen}
      onClose={() => {
        if (isCreating) return
        onClose()
      }}
      title={`Create ${scopeLabel} Topic`}
      size="sm"
      footer={
        <div className="flex justify-end gap-2 pt-2">
          <Button type="button" variant="secondary" onClick={onClose} disabled={isCreating}>
            Cancel
          </Button>
          <Button type="button" variant="primary" onClick={() => void handleCreate()} disabled={!canCreate || isCreating}>
            {isCreating ? 'Creating…' : 'Create'}
          </Button>
        </div>
      }
    >
      <form onSubmit={(e) => void handleCreate(e)} className="space-y-3">
        <div>
          <label className="block text-sm font-medium text-[var(--text-primary)] mb-1">
            Title
          </label>
          <input
            ref={inputRef}
            type="text"
            className="w-full px-3 py-2 border border-[var(--border-default)] rounded-md bg-[var(--surface-raised)] text-[var(--text-primary)] focus:outline-none focus:ring-2 focus:ring-[var(--accent-primary)]"
            placeholder="e.g. Planning, Architecture"
            value={title}
            onChange={(e) => setTitle(e.target.value)}
            autoFocus
            disabled={isCreating}
          />
        </div>

        {activeSelectionType === 'group' && !activeGroupId ? (
          <div className="text-xs text-[var(--text-secondary)]">Select a group to create a group topic.</div>
        ) : null}
        {activeSelectionType !== 'group' && !activeProjectId ? (
          <div className="text-xs text-[var(--text-secondary)]">Select a project to create a project topic.</div>
        ) : null}
      </form>
    </Modal>
  )
}
